export const KAKAO_AUTHORIZE = 'KAKAO_AUTHORIZE';
export const KAKAO_AUTHORIZE_SUCCESS = 'KAKAO_AUTHORIZE_SUCCESS';
export const KAKAO_AUTHORIZE_FAILURE = 'KAKAO_AUTHORIZE_FAILURE';

export const KAKAO_VERIFICATION = 'KAKAO_VERIFICATION';
export const KAKAO_VERIFICATION_SUCCESS = 'KAKAO_VERIFICATION_SUCCESS';
export const KAKAO_VERIFICATION_FAILURE = 'KAKAO_VERIFICATION_FAILURE';

export const KAKAO_LOGOUT = 'KAKAO_LOGOUT';
